### ISSUE TITLE
This fixes the different UV mapping used for Ruth2 feet.  (UVMAP to SLMAP).

### ISSUE THREAD

**Issue by JustCruising** [RuthAndRoth/Ruth2#3]
I don't really understand GitHub so I am nervous/unwilling to do a push/pull/whatever thing but if you want I will upload the changed version to my GitHub so you can DL it.

This fixes the different UV mapping used for Ruth2 feet.  (UVMAP to SLMAP).  It assumes the default blender settings for 3.65 .  It also can be done in 4.2 but you may have to mess with image selection in the UV workspace.

The process:

A) Go to UV Editing workspace, viewport shading set to 'Material preview'.
B) Outliner editor panel/window (view layer option set) select 'Ruth2v4'.
C) 3D Viewport editor panel/window, tab to Edit mode, deselect everything, tab to Object mode.

1: Outliner panel select 'Ruth2v4FeetFlat'.
2: 3D Viewport panel tab to Edit mode, ensure all (feet vertices) selected.
3: UV Editor panel, menu option 'UV', click 'Copy UVs'.
4: 3D Viewport tab to Object mode, select 'Ruth2v4FeetFlat', shift select body 'Ruth2v4', Ctrl-J to join.
5: Tab to edit mode, ensure feet selected, 'U' to UV Mapping, select 'Unwrap'.
6: UV Editor panel, 'A' select all, menu option 'UV", click 'Paste UV's'. 
7: Properties panel, Data tab, 'UV Maps' dropdown, select and delete 'UVMAP' leaving 'SLMAP'.
8: 3D Viewport press P select 'Selection', tab to Object mode.
9: Outliner panel select 'Ruth2v4.001' rename as 'Ruth2v4FeetFlat'.

Repeat steps 1 to 9 replacing Ruth2v4FeetFlat with Ruth2v4FeetHigh and then Ruth2v4FeetMedium.

I guess this method can be used for anything else has a UV map that is not the SLMAP used by the majority of the project.  Hope this is useful.

**Comment by aiaustin** [comment]
A good way to make a contribution is to put files into the "Contrib" area. Just add a directory there with your name and put the files in it. Add a suitable read me or description of the content.  Your issue text cut and pasted would be a good thing.  The idea is that this area can be used for any testing, variant creation and discussions that might lead to a future version of the released material.

https://github.com/RuthAndRoth/Ruth2/tree/master/Contrib

**Comment by JustCruising** [comment]
Hi thanks.

I am looking at that and have to 'fork' and 'push' it seems.  When I have worked out what I am forking (the contrib or the main thing) and how to do that and then the push thing, I will upload the file there.

Edit:

I sincerely hope this worked!  lol.  If not I hope you can undo things and https://github.com/JustCruising/Ruth2/tree/master holds the changes.

It did not allow me to upload the full thing with a "Yowza that is a big file" comment, so only the 3 sets of feet are in here.

BTW I could not find a way to add a directory and upload files, the options available were eventually taken and it ended up with a ruth2 in my github area and an option to pull (or push, I forget now which term).

**Comment by aiaustin** [comment]
Blender file and a readme put in https://github.com/RuthAndRoth/Ruth2/tree/master/Contrib/JustCruising
